# Generated by Django 2.2 on 2021-04-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210406_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='is_suth',
            new_name='is_auth',
        ),
    ]
